[target.x86_64-unknown-linux-musl]
pre-build = [
  "apt update",
  "apt install -y llvm-dev libclang-dev clang nasm"
]
[target.s390x-unknown-linux-gnu]
pre-build = [
  "apt update",
  "apt install -y llvm-dev libclang-dev clang nasm"
]
